version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: airbnb-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: airbnb
    ports:
      - "5432:5432"
    volumes:
      - airbnb_data:/var/lib/postgresql/data
      - ./src/sql:/docker-entrypoint-initdb.d 


volumes:
  airbnb_data: