version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: airbnb-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: airbnb
    ports:
      - "5432:5432"
    volumes:
      - airbnb_data:/var/lib/postgresql/data
      - ./src/sql:/docker-entrypoint-initdb.d 

  backend:
    build: .
    container_name: airbnb-backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: airbnb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

volumes:
  airbnb_data: